final List<Map<String, dynamic>> tenderList = [
  {
    "service": "Architectural Floor Plan",
    "createdAt": DateTime.now().subtract(Duration(minutes: 5)),
    "clientName": "Mr. Rajesh",
    "builtArea": "1200",
    "address": "Mumbai, Maharashtra",
    "floors": 1,
    "design": "Modern Design",
    "facing": "North Facing",
    "lastDate": DateTime.now().add(Duration(days: 1)),
    "unitPrice": "Rs. 4050 - Rs. 5000",
    "status": "Not Assigned",
    "assignedTO": "Mustkeem Baraskar",
    "completionStatus": "Not Assigned",
  },
  {
    "service": "3D Elevation Design",
    "createdAt": DateTime.now().subtract(Duration(minutes: 12)),
    "clientName": "Mr. Rajesh",
    "builtArea": "1200",
    "address": "Mumbai, Maharashtra",
    "floors": 1,
    "design": "Modern Design",
    "facing": "North Facing",
    "lastDate": DateTime.now().add(Duration(days: 1)),
    "unitPrice": "Rs. 4050 - Rs. 5000",
    "status": "Not Assigned",
    "assignedTO": "Mustkeem Baraskar",
    "completionStatus": "Not Assigned",
  },
  {
    "service": "Interior Design",
    "createdAt": DateTime.now().subtract(Duration(hours: 2)),
    "clientName": "Mrs. Shalini Verma",
    "builtArea": "1500",
    "address": "Bangalore, Karnataka",
    "floors": 2,
    "design": "Contemporary",
    "facing": "East Facing",
    "lastDate": DateTime.now().add(Duration(days: 3)),
    "unitPrice": "Rs. 3500 - Rs. 4500",
    "status": "Assigned",
    "assignedTO": "Akash Sinha",
    "completionStatus": "In Progress",
  },
  {
    "service": "Structural Engineering",
    "createdAt": DateTime.now().subtract(Duration(hours: 5)),
    "clientName": "Mr. Suresh Kumar",
    "builtArea": "2000",
    "address": "Chennai, Tamil Nadu",
    "floors": 3,
    "design": "Traditional",
    "facing": "South Facing",
    "lastDate": DateTime.now().add(Duration(days: 2)),
    "unitPrice": "Rs. 5000 - Rs. 6000",
    "status": "In review",
    "assignedTO": "Rohan Mehta",
    "completionStatus": "In Progress",
  },
  {
    "service": "Plumbing Layout",
    "createdAt": DateTime.now().subtract(Duration(hours: 10)),
    "clientName": "Mr. Amit Sharma",
    "builtArea": "800",
    "address": "Pune, Maharashtra",
    "floors": 1,
    "design": "Eco-Friendly",
    "facing": "West Facing",
    "lastDate": DateTime.now().add(Duration(days: 2)),
    "unitPrice": "Rs. 2500 - Rs. 3000",
    "status": "Assigned",
    "assignedTO": "Neha Patil",
    "completionStatus": "Completed",
  },
  {
    "service": "Electrical Layout",
    "createdAt": DateTime.now().subtract(Duration(hours: 3)),
    "clientName": "Mr. Karan Singh",
    "builtArea": "1400",
    "address": "Delhi, NCR",
    "floors": 2,
    "design": "Modern",
    "facing": "North-East Facing",
    "lastDate": DateTime.now().add(Duration(days: 3)),
    "unitPrice": "Rs. 3200 - Rs. 4000",
    "status": "Not Assigned",
    "assignedTO": "Mustkeem Baraskar",
    "completionStatus": "Not Assigned",
  },
  {
    "service": "Landscape Design",
    "createdAt": DateTime.now().subtract(Duration(minutes: 20)),
    "clientName": "Mrs. Anita Desai",
    "builtArea": "1000",
    "address": "Hyderabad, Telangana",
    "floors": 1,
    "design": "Minimalistic",
    "facing": "North Facing",
    "lastDate": DateTime.now().add(Duration(days: 4)),
    "unitPrice": "Rs. 2800 - Rs. 3500",
    "status": "In review",
    "assignedTO": "Rahul Nair",
    "completionStatus": "In Progress",
  }
];
