// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH9QHTNb0dvGNq_hj6_1cUhHVDwB6yGok',
    appId: '1:191195276308:web:51093f7c0c6f936486f301',
    messagingSenderId: '191195276308',
    projectId: 'b-designer-db',
    authDomain: 'b-designer-db.firebaseapp.com',
    databaseURL: 'https://b-designer-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'b-designer-db.firebasestorage.app',
    measurementId: 'G-7YXGPGC25G',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Qe4VE2OHwnx3EH4liysTYyvCl5tCTtQ',
    appId: '1:191195276308:web:3ab6418169dd7a2186f301',
    messagingSenderId: '191195276308',
    projectId: 'b-designer-db',
    authDomain: 'b-designer-db.firebaseapp.com',
    databaseURL: 'https://b-designer-db-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'b-designer-db.firebasestorage.app',
    measurementId: 'G-TTJ8ZBJHPX',
  );
}
